FROM pecan/executor:local

RUN install2.r -e -s -n -1 RPostgres plumber

COPY api /pecanapi
RUN rm -f /pecanapi/.Rprofile &&\
    Rscript -e 'devtools::install("/pecanapi")'

WORKDIR /pecanapi/inst

EXPOSE 8000
CMD R -e 'pr <- plumber::plumb("plumber.R"); pr$run(host="0.0.0.0", port=8000)'
